import type { ProjectPreview } from "../../types";

export default [
  {
    title: "Intelligent Voice Agent with Enterprise Integration",
    slug: "ai-voice-agent",
    thumbnail: "https://raw.githubusercontent.com/rupam13/Rupam_resume/main/public/images/thumbnails/ai-voice-agent.png",
    description: "60% call reduction | 24/7 availability | 80% first-contact resolution. Enterprise voice AI with autonomous decision-making.",
    category: "ai",
    metrics: [
      { label: "Call Reduction", value: 60, max: 100 },
      { label: "Availability", value: "24/7" },
      { label: "Resolution Rate", value: 80, max: 100 },
      { label: "Enterprise Ready", value: 95, max: 100 },
    ],
  },
  {
    title: "Cross-Department Efficiency Tracker & Power BI Savings Dashboard",
    slug: "efficiency-tracker-kpi",
    thumbnail: "https://raw.githubusercontent.com/rupam13/rupam-projects-data/main/images/ai/voice-agent.png",
    description: "MS Forms Data Collection | 1,200+ hrs saved/yr | Power BI Cost Analysis. Automated department efficiency tracker calculating time & dollar savings.",
    category: "ai",
    metrics: [
      { label: "Hours Reclaimed", value: 92, max: 100 },
      { label: "Annual Cost Savings", value: "$90K+" },
      { label: "Departments Tracked", value: "10/10" },
      { label: "Data Source", value: "MS Forms" },
    ],
  },
  {
    title: "Copilot Studio Live Agent Handoff & Time Telemetry Portal",
    slug: "copilot-handoff-portal",
    thumbnail: "https://raw.githubusercontent.com/rupam13/rupam-projects-data/main/images/ai/voice-agent.png",
    description: "12 mins saved/ticket | 100% transcript context | <1.2s handoff latency. Direct Line API escalation bridge to ServiceNow Agent Workspace (AWA).",
    category: "ai",
    metrics: [
      { label: "Handle Time Saved", value: 88, max: 100 },
      { label: "Transcript Context", value: 100, max: 100 },
      { label: "Handoff Latency", value: "<1.2s" },
      { label: "FCR Rate", value: 85, max: 100 },
    ],
  },
  {
    title: "Enterprise Invoice & Accounts Payable Automation",
    slug: "invoice-automation",
    thumbnail: "https://raw.githubusercontent.com/rupam13/Rupam_resume/main/public/images/thumbnails/invoice-automation.png",
    description: "85% processing time saved | 99% extraction accuracy | Zero manual entry errors. Automated AP pipeline with Power Automate, Azure AI & HITL approvals.",
    category: "ai",
    metrics: [
      { label: "Processing Speed", value: 85, max: 100 },
      { label: "Extraction Accuracy", value: 99, max: 100 },
      { label: "HITL Control", value: 100, max: 100 },
      { label: "Audit Compliance", value: 100, max: 100 },
    ],
  },
  {
    title: "Intelligent KYC & Identity Document Verification",
    slug: "kyc-processing",
    thumbnail: "https://raw.githubusercontent.com/rupam13/Rupam_resume/main/public/images/thumbnails/kyc-processing.png",
    description: "90% faster onboarding | 99.5% ID parsing accuracy | Secure & compliant. Automated identity document verification pipeline.",
    category: "ai",
    metrics: [
      { label: "Onboarding Speedup", value: 90, max: 100 },
      { label: "ID Extraction Accuracy", value: 99, max: 100 },
      { label: "Compliance Score", value: 100, max: 100 },
      { label: "Fraud Prevention", value: 95, max: 100 },
    ],
  },
  {
    title: "Autonomous Appointment Booking Assistant",
    slug: "ai-project-2",
    thumbnail: "https://raw.githubusercontent.com/rupam13/Rupam_resume/main/public/images/thumbnails/ai-appointment-booking.png",
    description: "70% no-show reduction | 90% auto-booked | 24/7 available. AI healthcare scheduling that eliminates manual work.",
    category: "ai",
    metrics: [
      { label: "No-Show Reduction", value: 70, max: 100 },
      { label: "Auto-Booked", value: 90, max: 100 },
      { label: "Availability", value: "24/7" },
      { label: "Efficiency", value: 85, max: 100 },
    ],
  },
  {
    title: "Intelligent Email Triage & Organization System",
    slug: "ai-project-3",
    thumbnail: "https://raw.githubusercontent.com/rupam13/Rupam_resume/main/public/images/thumbnails/ai-email-triage.png",
    description: "90% auto-sorted | 8 hours/week saved | Zero lost emails. Intelligent email organization powered by AI.",
    category: "ai",
    metrics: [
      { label: "Auto-Sorted", value: 90, max: 100 },
      { label: "Time Saved", value: "8hrs/week" },
      { label: "Accuracy", value: 92, max: 100 },
      { label: "Zero Lost Emails", value: 100, max: 100 },
    ],
  },
  {
    title: "Enterprise Policy Intelligence Assistant",
    slug: "ai-project-4",
    thumbnail: "https://raw.githubusercontent.com/rupam13/Rupam_resume/main/public/images/thumbnails/ai-policy-assistant.png",
    description: "95% instant answers | 80% less HR tickets | 24/7 available. Enterprise policy intelligence at your fingertips.",
    category: "ai",
    metrics: [
      { label: "Instant Answers", value: 95, max: 100 },
      { label: "HR Ticket Reduction", value: 80, max: 100 },
      { label: "Compliance Score", value: 98, max: 100 },
      { label: "Availability", value: "24/7" },
    ],
  },
  {
    title: "Intelligent Ticket Management & Resolution Platform",
    slug: "ticket-management",
    thumbnail: "https://via.placeholder.com/600x400/2e7d32/ffffff?text=🎫%20Ticket%20Mgmt",
    description: "85% SLA compliance | 40% faster resolution | Zero lost tickets. Intelligent ticket management system.",
    category: "servicenow",
    metrics: [
      { label: "SLA Compliance", value: 85, max: 100 },
      { label: "Speed Improvement", value: 40, max: 100 },
      { label: "Zero Lost Tickets", value: 100, max: 100 },
      { label: "Team Satisfaction", value: 88, max: 100 },
    ],
  },
  {
    title: "Intelligent Business Process Automation Engine",
    slug: "workflow-automation",
    thumbnail: "https://via.placeholder.com/600x400/4caf50/ffffff?text=⚙️%20Workflows",
    description: "70% cycle time reduction | 90% cost savings | Instant approvals. Transform manual processes into automated workflows.",
    category: "servicenow",
    metrics: [
      { label: "Cycle Time Reduction", value: 70, max: 100 },
      { label: "Cost Savings", value: 90, max: 100 },
      { label: "Process Consistency", value: 100, max: 100 },
      { label: "Approval Speed", value: 95, max: 100 },
    ],
  },
  {
    title: "ITIL-Compliant Incident Lifecycle Management",
    slug: "incident-management",
    thumbnail: "https://via.placeholder.com/600x400/009688/ffffff?text=🚨%20Incidents",
    description: "75% MTTR reduction | 100% incident tracking | Zero dropped issues. ITIL-compliant incident management.",
    category: "servicenow",
    metrics: [
      { label: "MTTR Reduction", value: 75, max: 100 },
      { label: "Incident Tracking", value: 100, max: 100 },
      { label: "ITIL Compliance", value: 100, max: 100 },
      { label: "Team Efficiency", value: 88, max: 100 },
    ],
  },
] as const satisfies ProjectPreview[];
